### PR TITLE
Added a missing action getReceiptStatus on Transaction

### PR DESCRIPTION
**Pull request by andrija-naglic**
Etherscan has an action that was missing in the Transaction class.
I did my best to follow your coding style and introduce the new method in that class.

### CODE REVIEW

**Comment by maslakoff** [comment]
Thank you a lot for contributing @dev-masta. Really appreciate it.

Could you please rename a function to getTransactionReceiptStatus? Otherwise looks good

**Comment by andrija-naglic** [comment]
No, thank you for creating the wrapper class in the first place :)

I have pushed the commit, that should do it @maslakoff

**Comment by maslakoff** [comment]
merged, thank you

**Comment by andrija-naglic** [comment]
@maslakoff what needs to be done to update the composer package?

**Comment by maslakoff** [comment]
@dev-masta it could be done using a PR for sure

**Pull request merged**
